FROM rocker/tidyverse:latest

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    libglpk-dev libxt-dev cmake build-essential libcurl4-openssl-dev libnode-dev libnlopt-dev

RUN R -q -e 'install.packages("pak")'
RUN R -q -e 'pak::pkg_install(c("dbscan","sf","geosphere","cluster", "geosphere", "rnaturalearth", "rnaturalearthdata", "fgsea", "hypeR", "brunnermunzel", "ggforce", "patchwork", "gt", "khroma", "Biostrings", "viridis", "gtools", "dunn.test", "fs", "ggokabeito", "ggtree", "ggtreeExtra", "ggnewscale", "Peptides", "lmerTest", "gluedown", "TreeDist", "Quartet", "cowplot", "ape", "phytools", "ggblend", "ggseqlogo", "bio3d", "colorspace", "plotwidgets", "PCAtools"))'
